### ISSUE TITLE
ERROR IN BAYOU.MCMC: error: matrix multiplication: incompatible matrix dimensions: 74x15 and 1x1 Error in C_weightmatrix(cache, pars) : matrix multiplication: incompatible matrix dimensions: 74x15 and 1x1

### ISSUE THREAD

**Issue by coyotree** [uyedaj/bayou#13]
Hello,

Thanks in advance for any help and thank you for your awesome tutorial on using this package. 

I was using an older version of bayou (1.1.0) earlier today and I got it to run smoothly with no problems. I then realized I was missing a lot of the functions in the documentation so I updated to the most recent version on GitHub (v 2.1). Now I am unable to get the bayou.mcmc function to work like I did earlier.

Using my data and following along with the tutorial you provided, I keep getting this error message when running bayou.mcmc:

`fit1 <- bayou.mcmc(bulb_size_tree, bulb_size.vector, SE = SE, model = "OU", prior, new.dir=getwd(), ngen = 10000)`
error: matrix multiplication: incompatible matrix dimensions: 74x15 and 1x1
Error in C_weightmatrix(cache, pars) : 
  matrix multiplication: incompatible matrix dimensions: 74x15 and 1x1

The prior and SE are the same as in the tutorial.

Any suggestions would be appreciated. Thanks for your time.

Thanks
Cody Coyotee

**Comment by coyotree** [comment]
Just wanted to add some evidence I did have it working earlier. :-)
[bayou_phenogram.pdf](https://github.com/uyedaj/bayou/files/2452246/bayou_phenogram.pdf)

**Comment by uyedaj** [comment]
Hi @coyotree, 
I had forgotten to notify the user that `bayou.mcmc` has been deprecated. Please use `bayou.makeMCMC`. For usage, please see: https://github.com/ssb2017/bayou/blob/master/R/bayouWorkshopNotebook.Rmd
