### ISSUE TITLE
Tutorial does not reflect updates

### ISSUE THREAD

**Issue by fishextinction** [uyedaj/bayou#15]
Currently, it looks like the tutorial does not function, because the package was updated to use a new 'bayou.makeMCMC'.

From what I can tell, this function does not actually start the MCMC sampler, nor is there any obvious documentation on how to do so.

**Comment by uyedaj** [comment]
Updated but need to make it prettier with output and everything. [But you can find it here.](https://github.com/uyedaj/bayou/blob/master/tutorial.md)
